language: java
jdk:
- oraclejdk8
services:
  - postgresql
branches:
  only:
  - master
script:
- ./gradlew clean checkstyleMain test cucumber
addons:
  postgresql: "9.6"
before_script:
    - psql -c 'create database hhpnet;' -U postgres