language: java
jdk:
- oraclejdk8
services:
  - postgresql
branches:
  only:
  - master
script:
- ./gradlew clean checkstyleMain test cucumber
before_script:
    - psql -c 'create database hhpnet;' -U postgres