language: java
jdk:
- oraclejdk8
services:
  - postgresql
branches:
  only:
  - master
script:
- ./gradlew clean checkstyleMain test cucumber
addons:
  postgresql: "9.6"
before_script:
  - cp src/main/resources/application-test.yml.travis src/main/resources/application-test.yml